[env]
NEXT_DAVE_IO_MISE_ACTIVE = 'true'

[settings]
env_file = '.env'
idiomatic_version_file = false
idiomatic_version_file_enable_tools = []


[tools]
bun = { version = '1.2.17' }
node = { version = '22.16.0' }
rust = { version = '1.87.0' }

[tasks]
'hello' = { run = "echo 'Hello, world!'" }
'claude' = { run = "bun x @anthropic-ai/claude-code", description = "Invoke the latest Claude Code" }
