[env]
NEXT_DAVE_IO_MISE_ACTIVE = 'true'

[settings]
env_file = '.env'

[tools]
node = { version = 'lts' }
bun = { version = '1.2.15' }
go = { version = '1.24.4' }
rust = { version = '1.87.0' }

[tasks]
'hello' = { run = "echo 'Hello, world!'" }
