name: ci

permissions: read-all

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.13
      - name: Install dependencies
        run: bun install
      - name: Run linting
        run: bun run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.13
      - name: Install dependencies
        run: bun install
      - name: Type check
        run: bun run typecheck