name: ci
permissions: read-all
on:
  push: null
  pull_request: null
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
      - name: bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76
        with:
          bun-version: 1.2.15
      - name: install
        run: bun install
      - name: typecheck
        run: bun run typecheck
      - name: biome
        run: bun run biome check
      - name: trunk
        uses: trunk-io/trunk-action@75699af9e26881e564e9d832ef7dc3af25ec031b
