name: ci
permissions: read-all
on:
  push:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.13
      - name: install
        run: bun install
      - name: lint
        run: bun run lint
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.13
      - name: install
        run: bun install
      - name: typecheck
        run: bun run typecheck